### ISSUE TITLE
Inibir print do stacktrace quando validação de campo é falsa

### ISSUE THREAD

**Issue by dhiogocorrea** [gilmardeveloper/java-validator-safeguard#5]
Quando é realizada a validação de algum tipo, e essa validação é falsa, automaticamente é printado o stacktrace da exceção IllegalStateException. 

Seria bom se pudéssemos passar uma flag na construção do Check dizendo se quer ou não printar o stacktrace.

**Comment by gilmardeveloper** [comment]
Opa Diogo fico feliz que tenham pessoas utilizando minha biblioteca, e ainda mais, quando estão sugerindo melhorias. Vou implementar sua sugestão na nova versão, agradeço pelo feedback, abraço.
